[package]
name = "post_parser"
version = "0.1.0"
authors = ["Inno Jia <jdgets111@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "^0.6.0"