[package]
name = "docs"
version = "0.1.0"
authors = ["Inno Jia <jdgets111@gmail.com>"]
edition = "2018"
description = "A cargo doc and `crate.io` usage demo"
license = 'MIT OR Apache-2.0cat'

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3