[package]
name = "actix-web-demo"
version = "0.1.0"
authors = ["Inno Jia <jdgets111@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-http = "1.0.1"
listenfd = "0.3"